export * from './hero';
export * from './features';
export * from './pricing';
export * from './morefeatures';
export * from './howitworks';
export * from './contact';
export * from './faqs';
export * from './navbar';
export * from './footer';
